### PR TITLE
add styles

### PR DESCRIPTION
**Pull request by aholtzman**
update styling

### CODE REVIEW

**Review by thescientist13 — APPROVED** [review]
I think this passes the vibe check!

----

Only thought that comes to mind is do we feel it might be helpful to bootstrap user's with something like a _theme.css_ with some CSS custom properties / variables?

I know we're still working things out there in [Greenwood re: design systems](https://github.com/ProjectEvergreen/greenwood/discussions/800) but I feel like that would be a quick way to demonstrate a very new and powerful CSS feature that I think deserves more love in front end projects, especially ones in the space of Web Components?

Doesn't have to be a whole design system, just a handful of variables like we did here.
https://github.com/thescientist13/greenwood-starter-presentation/blob/master/src/styles/theme.css

**Comment by aholtzman** [comment]
updated to use some css variables

**Comment by aholtzman** [comment]
It may be an additional enhancement to this template to have the blog sidebar be a component that renders out the list of posts based on the contents of the 'blog' directory. Just a thought.

**Review by hutchgrant — APPROVED** [review]
lgtm

**Pull request merged**
